name: GitHub Actions Demo
on: [ push ]
jobs:
  # 任务id，必须是jobs下唯一的
  accessibility_test:
    # 运行所需要的虚拟机环境。例如 windows-2019, macOS-latest、macOS-10.14
    runs-on: macos-latest
    # job的运行步骤
    steps:
      # 便于获取flutter源码
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # 设置flutter环境
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'
          channel: 'stable'  # or: 'dev' or 'beta'
        # 运行的命令
      - run: "flutter pub get"
        # 步骤名称
      - name: "Run Flutter Accessibility Tests"
        run: "flutter test"


